apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: func-deploy
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: CLI
    tekton.dev/tags: cli
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This Task performs a deploy operation using the Knative `func` CLI
  params:
    - name: path
      description: Path to the function project
      default: ""
    - name: image
      description: Container image to be deployed
      default: ""
  workspaces:
    - name: source
      description: The workspace containing the function project
  steps:
    - name: func-deploy
      image: "quay.io/mvasek/func-util:latest@sha256:1e33ad898019ccc76049a7e1e2cd7f3d704def1d013f11757f50ce95cb874485"
      script: |
        func deploy --verbose --build=false --push=false --path=$(params.path) --remote=false --image="$(params.image)"
