apiVersion: v1
kind: ServiceAccount
metadata:
  name: knative-deployer-account
  namespace: default
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default:knative-deployer-binding
subjects:
- kind: ServiceAccount
  name: knative-deployer-account
roleRef:
  kind: ClusterRole
  name: kn-deployer
  apiGroup: rbac.authorization.k8s.io
