name: Func Check Source

on: [pull_request]

jobs:
  check:
    name: Check Source
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/composite/go-setup
      - name: Check
        run: make check

