name: Func Schema Check

on: [pull_request]

jobs:
  check:
    name: Check Schema
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/composite/go-setup
      - name: Check 'func.yaml'
        run: make schema-check
