name: Docker Info

on: [pull_request]

jobs:
  test:
    name: Docker Info
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Docker Version
        run: docker version
      - name: Docker Info
        run: docker info
      - name: Print Config
        run: cat /etc/docker/daemon.json
