name: Docker Info

on: [pull_request]

jobs:
  test:
    name: Docker Info
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Docker Version
        run: docker version
      - name: Docker Info
        run: docker info
      - name: Build
        run: pwd; docker build .
