name: Template Test Debug

on: [pull_request]

jobs:
  test:
    name: Quarkus Template Test
    strategy:
      matrix:
        go: [1.18.x]
        java: [17]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Quarkus Template Test
        run: make test-quarkus
