name: Func Unit Test

on: [pull_request]

jobs:
  test:
    name: Unit Test 
    strategy:
      matrix:
        go: [1.18.x]
        java: [11]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Bash 4 on Mac
        if: matrix.os == 'macos-latest'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update

          brew install bash
          brew install gnu-sed

          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Core Unit Tests
        run: make test
      - name: Template Unit Tests
        run: make test-templates
