name: Func Unit Test

on: [pull_request]

jobs:
  test:
    name: Unit Test
    strategy:
      matrix:
        java: [21]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Bash 4 on Mac
        if: matrix.os == 'macos-latest'
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew update

          brew install bash
          brew install gnu-sed

          echo "/usr/local/bin" >> $GITHUB_PATH
          echo "$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: ./.github/composite/go-setup
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
      - name: Core Unit Tests
        run: make test
        env:
          FUNC_REPO_REF: ${{ github.event.pull_request.head.repo.full_name }}
          FUNC_REPO_BRANCH_REF: ${{ github.head_ref }}
      - name: Template Unit Tests
        run: make test-templates
      - name: "Archive code coverage results"
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}
          path: ./coverage.txt
          retention-days: 1
  upload-coverage:
    needs: [test]
    name: "Upload coverage"
    runs-on: "ubuntu-latest"
    steps:
      - name: Download Coverage
        run: |
          gh run download -R ${{ github.repository }} ${{ github.run_id }}
          curl "https://raw.githubusercontent.com/${{ github.event.pull_request.head.repo.full_name }}/${{ github.head_ref }}/.codecov.yaml" > .codecov.yaml
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: codecov/codecov-action@v4
        with:
          files: ./coverage-ubuntu-latest/coverage.txt,./coverage-windows-latest/coverage.txt,./coverage-macos-latest/coverage.txt
          flags: unit-tests
