name: Func E2E OnCluster RT Test

on: [pull_request]

jobs:
  test:
    name: On Cluster RT Test
    continue-on-error: true
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        func_builder: ["pack", "s2i"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/composite/go-setup
      - uses: imjasonh/setup-ko@v0.6
      - name: Install Binaries
        run: ./hack/binaries.sh
      - name: Allocate Cluster
        run: ./hack/allocate.sh
      - name: Setup testing images
        run: ./hack/setup-testing-images.sh
      - name: Deploy Tekton
        run: ./hack/tekton.sh
      - name: Deploy Test Git Server
        run: ./test/gitserver.sh
      - name: E2E On Cluster Test (Runtimes)
        env:
          TEST_TAGS: runtime
          E2E_REGISTRY_URL: registry.default.svc.cluster.local:5000
          FUNC_REPO_REF: ${{ github.event.pull_request.head.repo.full_name }}
          FUNC_REPO_BRANCH_REF: ${{ github.head_ref }}
          FUNC_BUILDER: ${{ matrix.func_builder }}
        run: make test-e2e-on-cluster
      - name: Dump Cluster Logs
        if: always()
        run: |
          echo "::group::cluster events"
          kubectl get events -A
          echo "::endgroup::"

          echo "::group::cluster containers logs"
          stern '.*' --all-namespaces --no-follow
          echo "::endgroup::"
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          flags: e2e-test-oncluster-runtime
