name: Func E2E OnCluster RT Test

on: [pull_request]

jobs:
  test:
    name: On Cluster RT Test
    strategy:
      matrix:
        go: [1.20.2]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: imjasonh/setup-ko@v0.6
      - name: Patch S2I Task
        run: ./hack/patch-s2i-task.sh
      - name: Install Binaries
        run: ./hack/binaries.sh
      - name: Setup testing func image
        run: ./hack/create-testing-func-image.sh
      - name: Allocate Cluster
        run: ./hack/allocate.sh
      - name: Deploy Tekton
        run: ./hack/tekton.sh
      - name: Deploy Test Git Server
        run: ./test/gitserver.sh
      - name: E2E On Cluster Test (Runtimes)
        env:
          TEST_TAGS: runtime
          E2E_REGISTRY_URL: registry.default.svc.cluster.local:5000
          FUNC_REPO_REF: ${{ github.event.pull_request.head.repo.full_name }}
          FUNC_REPO_BRANCH_REF: ${{ github.head_ref }}
        run: make test-e2e-on-cluster
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          flags: e2e-test-oncluster-runtime
