name: Update Kn components (allocate.sh)

permissions:
  contents: write
  pull-requests: write

# on:
  # schedule:
  # - cron: '0 */4 * * *'
jobs:
  update:
    name: Update to latest
    runs-on: ubuntu
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: 1.23.4
    - name: Run script
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: go run ./hack/main.go "update-components"

