name: Update Quarkus Platform in embedded templates

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 */4 * * *'

jobs:
  update:
    name: Update Quarkus Platform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/composite/go-setup
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Install NPM deps.
        run: npm install xml2js octokit@3.2.1
      - name: Create PR
        with:
          delete-branch: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: node ./hack/update-quarkus-platform.js

